default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bailiff_development
  user: user
  password: qwerty

test:
  <<: *default
  database: bailiff_test

production:
  <<: *default
  database: bailiff_production
  username: bailiff
  password: <%= ENV['BAILIFF_DATABASE_PASSWORD'] %>
